version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pki-2fa-app
    ports:
      - "8080:8080"
    environment:
      - TZ=UTC
      - DATA_DIR=/data
    volumes:
      - seed-data:/data
      - cron-output:/cron
      - ./student_private.pem:/srv/app/student_private.pem:ro
      - ./student_public.pem:/srv/app/student_public.pem:ro
      - ./instructor_public.pem:/srv/app/instructor_public.pem:ro
    restart: unless-stopped

volumes:
  seed-data:
  cron-output:
